name: Debug Files
on: [push, pull_request]

jobs:
  diagnostico:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Listar estrutura de pastas
        run: |
          echo "--- Onde estou? ---"
          pwd
          echo "--- O que tem aqui? ---"
          find . -maxdepth 3 -not -path '*/.*'